### ISSUE TITLE
Problem extraction

### ISSUE THREAD

**Issue by Jean-BaptisteC** [U039b/aosp_permissions_extraction#4]
Test on Debian 9 and Debian 11, same issue

`Traceback (most recent call last):`
`File "/usr/local/bin/extract_aosp/permissions.py", line 149, in <module> groups = extract_permission_groups(aosp_root_dir)`
`File "/usr/local/bin/extract_aosp/permissions.py", line 47, in extract_permission_groups`
`'request_ptr': str(g.attributes['android:request'].value.replace('@string/', '')),`
`File "/usr/lib/python3.9/xml/dom/minidom/py", line 553, in __getitem__ return self._attrs[attname_or_tuple]`
`KeyError: 'android:request'`

**Comment by U039b** [comment]
Could you please tell me the commit hash of AOSP you are trying to extract permissions from?

**Comment by Jean-BaptisteC** [comment]
From Android 11, request_ptr on permission_group is delete from AndroidManifest.xml
